-- ============================================================
-- AI 学生折扣站 - 数据库初始化脚本 (支持 Cloudflare D1 与 SQLite)
-- ============================================================

CREATE TABLE IF NOT EXISTS deals (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  vendor TEXT NOT NULL,
  letter TEXT DEFAULT '',
  brand TEXT DEFAULT '["#8b7cff","#38e0c8"]',
  category TEXT NOT NULL,
  tier TEXT DEFAULT 'A',
  status TEXT DEFAULT 'conditional',
  review_status TEXT DEFAULT 'approved',
  value TEXT DEFAULT '—',
  value_num REAL DEFAULT 0,
  duration TEXT DEFAULT '学生期内有效',
  deadline TEXT DEFAULT '',
  cn TEXT DEFAULT 'partial',
  difficulty INTEGER DEFAULT 3,
  tags TEXT DEFAULT '[]',
  summary TEXT DEFAULT '',
  highlights TEXT DEFAULT '[]',
  notes TEXT DEFAULT '',
  need TEXT DEFAULT '{"edu":true,"sheerid":false,"card":false,"vpn":false}',
  url TEXT NOT NULL,
  contact TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_deals_review_status ON deals (review_status);
CREATE INDEX IF NOT EXISTS idx_deals_category ON deals (category);
CREATE INDEX IF NOT EXISTS idx_deals_tier ON deals (tier);

INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('gemini', 'Google Gemini 学生计划', 'Google', 'G', '["#4285f4","#34a853","#fbbc05","#ea4335"]', 'ai', 'S', 'hot', 'approved', '$239.88', 239.88, '免费 12 个月', '2026-12-31', 'partial', 2, '["12个月","5TB 存储","Deep Research"]', '美国大学生可免费领取 12 个月 Google AI Pro；美国以外 140+ 市场主要对应 Google AI Plus 学生权益。', '["🇺🇸 Google AI Pro 免费 12 个月，价值 $19.99/月 × 12","Gemini 高级模型 + 更高使用额度 + Deep Research","5TB Google One 存储（美国）/ 400GB（其他市场）","Gmail / Docs 内的 Google AI 能力","学习工具：Study Notebook、Flashcards、Practice Quiz","含标准化考试练习测验（ACT/AP/GRE/LSAT/MCAT/SAT/JEE/NEET 等，与 The Princeton Review 等合作）","Gemini 与 Google 搜索内可生成交互式 3D 可视化，辅助理解生物/物理难点"]', '2026-08-19 重新开放，美国学生需在 2026-12-31 前完成领取。条件：年满 18 岁、受认可高校在读、通过学生身份验证，并绑定有效支付方式（激活时不扣费）。⚠️ 自动续费：免费期结束后会按标准价（美国 $19.99/月）自动转为付费订阅，务必在到期前取消或设提醒。明确排除地区包括 Bolivia、Albania、Canada、Tunisia 以及中国香港、中国澳门，申请前先确认所在市场是否在名单内。部分地区另有 Google AI Pro + YouTube Premium 捆绑折扣（最高约 70% off）。', '{"edu":true,"sheerid":true,"card":false,"vpn":true}', 'https://gemini.google.com/students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('chatgpt', 'ChatGPT Plus 学生优惠', 'OpenAI', 'AI', '["#10a37f","#1a7f64"]', 'ai', 'S', 'hot', 'approved', '$80', 80, '免费 4 个月', '2026-10-31', 'hard', 3, '["4个月","$20/月","SheerID"]', '符合条件的美国大学生/研究生可免费获得 4 个月 ChatGPT Plus，需在 2026-10-31 前通过 SheerID 认证。', '["免费 4 个月 ChatGPT Plus，价值 4 × $20 = $80","本科 / 研究生，全日制或非全日制均可","需美国符合资格院校 + SheerID 学生认证","ChatGPT 邮箱与学校邮箱不要求一致","若所在学校已加入 ChatGPT Edu，通常可直接免费用到 Plus 级功能"]', '⚠️ 存在信息冲突：OpenAI 官方帮助中心列有返校季学生优惠，但多家第三方 2026-08 评测称 ChatGPT Plus 的长期学生折扣早在 2025-05 结束、目前并无全球学生档，且 OpenAI 任何套餐都不支持年付。申请前务必先打开官方页面确认是否仍在发放，别按旧攻略白跑。替代路线：ChatGPT Go $8/月（最便宜官方档）、ChatGPT Edu（学校在名单内则学生免费）、Codex $100 学生额度（美加）。', '{"edu":true,"sheerid":true,"card":false,"vpn":true}', 'https://help.openai.com/en/articles/20001493-chatgpt-back-to-school-offer-for-students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('codex', 'ChatGPT Codex 学生额度', 'OpenAI', 'CX', '["#10a37f","#0d8f6f"]', 'ai', 'S', 'hot', 'approved', '$100', 100, '额度有效期 12 个月', '', 'hard', 3, '["$100 额度","2500 credits","仅美加"]', '美国和加拿大符合条件的大学生可获得 $100 Codex Credits（官方称 2,500 credits），用于 AI 编程与 Agent 任务。', '["$100 Codex 使用额度（约 2,500 credits）","适用于 Codex、AI 编程、代码生成与修改、自动执行编程任务","这是 ChatGPT/Codex 内额度，不是 OpenAI API 余额","获得后 12 个月内有效"]', '目前仅限 🇺🇸 美国 / 🇨🇦 加拿大。对程序员学生而言价值甚至高于 Plus 优惠。', '{"edu":true,"sheerid":true,"card":false,"vpn":true}', 'https://chatgpt.com/codex/students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('claude', 'Claude 学生活动', 'Anthropic', 'C', '["#d97757","#c15f3c"]', 'ai', 'A', 'conditional', 'approved', '—', 0, '活动周期型', '', 'hard', 4, '["活动型","需自查"]', 'Claude 未推出长期统一的全球学生计划，多为阶段性教育合作活动，申请前请以官方当前页面为准。', '["适合长文写作、论文润色、代码重构","关注开学季 / 校园合作活动窗口","建议配合 GitHub Student Pack 渠道关注"]', '⚠️ 已核实：Anthropic 目前没有面向个人的公开学生折扣，Pro 全球统一定价 $20/月（年付折算 $17/月）。教育路线只有两条：一是学校与 Anthropic 签了 Claude for Education（学生通常可通过校园账号免费用），二是 Claude for Startups（需先注册公司）。研究人员可关注 Claude for Science 的 Team 计划（由 PI/实验室申请，学生不单独申请）。预算有限就用免费档或按量 API（轻度使用约 $3–5/月）。', '{"edu":true,"sheerid":false,"card":true,"vpn":true}', 'https://claude.ai', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('perplexity', 'Perplexity 学生计划', 'Perplexity', 'P', '["#20b8cd","#1a8ba0"]', 'search', 'A', 'conditional', 'approved', '—', 0, '地区/活动周期型', '', 'partial', 3, '["深度搜索","论文引用","活动型"]', '写论文、查文献、做深度研究的利器，学生优惠属于地区/活动周期型，当前能认证就值得申请。', '["论文检索与来源引用，适合学术写作","深度搜索 Deep Research 模式","新闻、资料、事实核查一站式"]', '学生权益为地区/活动周期型。公开信息中 Education Pro 约 $10/月（SheerID 验证，原价 $20），也有 $4.99/月 的说法，差异来自活动批次与地区，以官方 Students 页面当前显示为准。年付通常再省 15%–20%。', '{"edu":true,"sheerid":false,"card":true,"vpn":true}', 'https://www.perplexity.ai/students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('github-pack', 'GitHub Student Developer Pack', 'GitHub', 'GH', '["#6e40c9","#8b7cff"]', 'devpack', 'S', 'hot', 'approved', '$400+ 权益', 400, '学生身份持续有效', '', 'ok', 2, '["80+ 资源","薅羊毛之王","2年复验"]', '学生薅羊毛之王。官方称包含 80+ resources，大量免费/学生专享权益，且合作伙伴权益持续变化。', '["80+ 开发者资源与合作伙伴权益","含 Copilot、Notion、Overleaf、域名、云额度等入口","学生身份持续有效，验证有效期约 2 年","中国大陆高校邮箱多数可直接通过验证","DigitalOcean $200 额度、Azure $100 额度、Namecheap 免费 .me 域名 + SSL","1Password 免费一年、Educative 6 个月课程、MongoDB Atlas 额度、Heroku 额度"]', '官方条款明确：验证有效期约 2 年，之后需重新验证；第三方优惠不可通过反复注册账号重复领取。门槛很友好：13 岁以上、在读学位/文凭课程即可，学校邮箱域名被识别通常几分钟通过，未识别则上传带日期的学生证或在读证明走人工审核（数天）。毕业后 Pack 权益停止续期，若创业可转 GitHub for Startups。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://education.github.com/pack', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('github-pro', 'GitHub Pro（学生免费）', 'GitHub', 'PRO', '["#4a5568","#2d3748"]', 'devpack', 'S', 'hot', 'approved', '$48/年', 48, '学生期间免费', '', 'ok', 1, '["私有仓库","Codespaces","Actions"]', '学生认证后免费获得 GitHub Pro，解锁私有仓库高级能力、Codespaces、Actions 等付费功能。', '["私有仓库高级能力","Codespaces 云端开发环境额度","GitHub Actions 高级额度","协作与代码审查增强"]', '随 Student Developer Pack 一并生效，是最容易拿到的权益之一。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://docs.github.com/en/billing/concepts/discounted-plans', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('copilot', 'GitHub Copilot Student', 'GitHub', 'CP', '["#3ddc97","#2aa876"]', 'coding', 'S', 'hot', 'approved', '$120+/年', 120, '学生期间免费', '', 'ok', 2, '["无限补全","Agent","AI Credits"]', 'Student Pack 中最重要的权益之一：无限代码补全 + Chat + Agent 能力 + 一定额度 GitHub AI Credits。', '["Unlimited code completions","Copilot Chat、多文件修改、Codebase 理解","Agent 能力与自动 Debug","一定额度的 GitHub AI Credits","代码补全与 next edit 建议不消耗 AI Credits，在所有付费档都是 unlimited"]', '需先通过 GitHub Education 学生验证。⚠️ 2026 年 4 月 GitHub 曾因 agentic 工作负载超出定价承受范围而暂停 Copilot Student 新注册，6 月中才逐步重开；若你的 Pack 已通过但 Copilot 仍显示为 Free，通常是灰度放行延迟而不是被拒，其余权益不受影响。补充：验证通过的教师与热门开源项目维护者同样可获得免费 Copilot Pro。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://education.github.com/pack', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('cursor', 'Cursor Student', 'Cursor', 'CU', '["#5b8def","#3f6fd8"]', 'coding', 'A', 'conditional', 'approved', '$100', 100, '学生专属优惠', '', 'partial', 3, '["AI IDE","Agent Coding","动态活动"]', 'AI Coding 学生党必关注：Agent、多文件修改、Codebase 理解、AI Debug、自动生成代码。', '["AI Coding 与 Agent 模式","多文件修改与代码库理解","AI Debug 与自动代码生成"]', '⚠️ 重要风险：有 2026-09 的行业报道称 Cursor 已于 2026 年 6 月因欺诈问题终止学生计划，这与「仍可领一年 Pro 免费」的说法直接冲突。申请前一定要打开 cursor.com/students 看当前页面是否还开放，不要照旧攻略操作。若已关闭，可转向 Windsurf（学生价约 $6.9/月）、AWS Kiro（学生免费一年）、GitHub Copilot Student。', '{"edu":true,"sheerid":false,"card":true,"vpn":true}', 'https://cursor.com/students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('jetbrains', 'JetBrains 学生许可证', 'JetBrains', 'JB', '["#fe315d","#c11e42"]', 'coding', 'S', 'hot', 'approved', '$200+/年', 200, '学生期间免费', '', 'ok', 2, '["全家桶","免费授权","一年可续"]', '免费学生许可证覆盖大量 JetBrains IDE：Java / Kotlin / Python / Go / C++ / Web / 数据科学全覆盖。', '["IntelliJ IDEA、PyCharm、WebStorm","GoLand、CLion、DataGrip、Rider","可用学校邮箱或在读证明申请，大陆高校通常可过"]', '每年续期，需保持学生身份有效。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://www.jetbrains.com/community/education/#students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('replit', 'Replit Education', 'Replit', 'RP', '["#f26207","#c94e05"]', 'coding', 'A', 'conditional', 'approved', '—', 0, '学生/教育权益动态调整', '', 'partial', 3, '["在线 IDE","快速部署","动态权益"]', 'AI Coding + Agent + 在线 IDE + 快速部署，适合做 Web App 与 SaaS Demo。', '["在线 IDE 与一键部署","AI Agent 辅助开发","适合 AI Agent 产品原型"]', '学生/教育权益动态调整，需查看当前活动。', '{"edu":true,"sheerid":false,"card":false,"vpn":true}', 'https://replit.com/education', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('azure', 'Azure for Students', 'Microsoft', 'AZ', '["#0078d4","#005a9e"]', 'cloud', 'S', 'hot', 'approved', '$100', 100, '额度有效期 12 个月', '', 'partial', 2, '["$100 额度","免信用卡","含 Azure OpenAI"]', '$100 Azure Credit，12 个月有效，且不需要信用卡。适合部署 AI Agent、网站、API、Bot、SaaS、RAG。', '["$100 Azure Credit，12 个月有效","无需信用卡即可开通","20+ 热门服务免费额度 + 65+ 永久免费服务","可用于 Azure OpenAI、云服务器、数据库、Storage、Functions、Container"]', '学生自建服务最值得拿的一档，大陆学生需准备可用的手机号/邮箱与网络环境。', '{"edu":true,"sheerid":false,"card":false,"vpn":true}', 'https://azure.microsoft.com/free/students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('aws-educate', 'AWS Educate', 'Amazon', 'AWS', '["#ff9900","#cc7a00"]', 'cloud', 'A', 'hot', 'approved', '免费', 0, '长期免费', '', 'partial', 2, '["免费","学习路径","实验"]', 'AWS Educate 对个人免费开放，重点在云计算 / AI / ML 学习路径与实验，而非传统会员权益。', '["免费开放，含学习路径与动手实验","覆盖 AWS 云计算、AI、ML","EC2、S3、数据库等云开发实践"]', '适合打云基础，配合 Azure $100 使用更佳。', '{"edu":true,"sheerid":false,"card":false,"vpn":true}', 'https://aws.amazon.com/education/awseducate/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('gcp-edu', 'Google Cloud Education', 'Google Cloud', 'GCP', '["#4285f4","#1a73e8"]', 'cloud', 'A', 'conditional', 'approved', '—', 0, '学生/课程计划', '', 'partial', 3, '["教育额度","课程计划"]', 'Google Cloud 提供学生/课程/教育计划额度，适合需要 GPU 与 AI 平台（Vertex AI）的同学。', '["学生/课程计划额度","可用 Vertex AI、BigQuery、Cloud Run","部分计划提供 GPU 额度"]', '以官方教育页面当前政策为准。', '{"edu":true,"sheerid":false,"card":true,"vpn":true}', 'https://cloud.google.com/edu', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('m365', 'Microsoft 365 学生版', 'Microsoft', 'M', '["#d83b01","#a82c01"]', 'office', 'S', 'hot', 'approved', '$120', 120, '12 个月 Premium', '', 'partial', 2, '["12个月 Premium","含 Copilot 折扣","Web 版免费"]', '美国大学生可用学校邮箱领取 12 个月 Microsoft 365 Premium；同时长期提供免费 Web 版 Word/Excel/PowerPoint。', '["免费 Microsoft 365 Web：Word / Excel / PowerPoint","限时：大学生可领 12 个月 Microsoft 365 Premium","部分市场提供 Microsoft 365 with Copilot 5 折"]', '2026 年学生权益有变化，值得先查官方学生中心。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://www.microsoft.com/en-us/education/students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('notion', 'Notion for Education', 'Notion', 'N', '["#6b7280","#374151"]', 'office', 'A', 'hot', 'approved', '$60', 60, '教育计划', '', 'ok', 1, '["知识库","Second Brain","AI 工作流"]', '教育计划适合课程管理、知识库、论文、项目与 AI 工作流搭建，GitHub Student Pack 也含对应权益入口。', '["课程管理与知识库","论文与项目管理","Second Brain 与 AI 工作流","GitHub Student Developer Pack 内含 Notion 权益"]', '学校邮箱申请通常秒过。⚠️ 注意：教育版主要解锁页面数、30 天版本历史、文件上传与站点发布等限制，完整 Notion AI 已并入 Business 计划（约 $20/用户/月），教育版只有额度有限的「 complimentary AI responses 」，重度 AI 使用不要指望它。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://www.notion.com/product/notion-for-education', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('overleaf', 'Overleaf 学生计划', 'Overleaf', 'O', '["#47a141","#2f7a2b"]', 'learn', 'A', 'hot', 'approved', '$40', 40, 'Student / Education', '', 'ok', 1, '["LaTeX","SCI/IEEE","协作论文"]', '论文党必备：SCI / IEEE / LaTeX / 毕业论文 / 协作写论文，GitHub Student Pack 也提供权益入口。', '["LaTeX 在线协作写作","大量期刊/会议模板（IEEE、Springer 等）","GitHub Student Developer Pack 提供权益入口"]', '研究生与科研人员优先级很高。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://www.overleaf.com/edu/students', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('kaggle', 'Kaggle', 'Google', 'K', '["#20beff","#0d8ecf"]', 'learn', 'B', 'free', 'approved', '免费', 0, '永久免费', '', 'ok', 1, '["免费 GPU","数据集","竞赛"]', '机器学习 / LLM / 数据科学方向几乎应该直接注册，提供免费算力、数据集与竞赛。', '["免费 Notebook 算力（含 GPU）","海量公开数据集","竞赛与学习课程"]', '零门槛，直接注册即可。', '{"edu":false,"sheerid":false,"card":false,"vpn":false}', 'https://www.kaggle.com', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('colab', 'Google Colab', 'Google', 'CO', '["#f9ab00","#e37400"]', 'learn', 'B', 'free', 'approved', '免费层', 0, '永久免费层', '', 'partial', 1, '["免费 GPU","Notebook"]', '免费层即可用 GPU 跑模型实验，AI 学习阶段最省钱的算力来源。', '["免费 GPU / TPU 额度（动态）","Jupyter Notebook 环境","与 Google Drive 深度集成"]', '需要可用的网络环境。', '{"edu":false,"sheerid":false,"card":false,"vpn":true}', 'https://colab.research.google.com', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('huggingface', 'Hugging Face', 'Hugging Face', 'HF', '["#ffd21e","#e0a800"]', 'learn', 'B', 'free', 'approved', '免费/学生计划', 0, '长期', '', 'ok', 1, '["模型库","免费托管"," Spaces"]', '模型与数据集生态核心，免费层即可托管 Demo、下载模型，学生相关计划持续更新。', '["海量开源模型与数据集","Spaces 免费托管 AI Demo","推理 API 与社区资源"]', 'AI 学生必备基础设施。', '{"edu":false,"sheerid":false,"card":false,"vpn":false}', 'https://huggingface.co', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('datacamp', 'DataCamp 学生权益', 'DataCamp', 'DC', '["#03ef62","#02b84a"]', 'learn', 'B', 'discount', 'approved', '—', 0, '学生优惠', '', 'partial', 2, '["数据科学","课程"]', '数据科学与 AI 课程平台，提供学生专属优惠价。', '["Python / SQL / ML 体系课程","学生专属折扣"]', '以官方教育页当前价格为准。', '{"edu":true,"sheerid":false,"card":true,"vpn":false}', 'https://www.datacamp.com', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('coursera', 'Coursera 学生/地区优惠', 'Coursera', 'CR', '["#0056d2","#003d94"]', 'learn', 'B', 'discount', 'approved', '—', 0, '部分学校/地区', '', 'partial', 2, '["名校课程","证书"]', '部分学校与地区提供优惠，可通过学校邮箱或校园计划获取折扣。', '["名校与企业课程","部分学校提供免费授权"]', '先看自己学校是否有 Campus 计划。', '{"edu":true,"sheerid":false,"card":true,"vpn":false}', 'https://www.coursera.org', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('edx', 'edX', 'edX', 'eX', '["#02262b","#0d4d54"]', 'learn', 'B', 'discount', 'approved', '—', 0, '学习内容/优惠', '', 'partial', 2, '["MOOC","微硕士"]', '大量免费旁听课程，证书部分提供学生优惠。', '["MIT / Harvard 等课程","免费旁听 + 付费证书"]', '旁听通常免费，证书按需购买。', '{"edu":false,"sheerid":false,"card":true,"vpn":false}', 'https://www.edx.org', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('nvidia-dli', 'NVIDIA 深度学习学院', 'NVIDIA', 'NV', '["#76b900","#5c8f00"]', 'learn', 'B', 'discount', 'approved', '—', 0, '部分课程优惠', '', 'partial', 3, '["GPU","认证","部分优惠"]', '部分课程提供学生/教育优惠，适合深入 CUDA、LLM、机器人方向。', '["官方深度学习与加速计算课程","部分课程教育优惠"]', '关注官方教育与学生计划页。', '{"edu":true,"sheerid":false,"card":true,"vpn":true}', 'https://www.nvidia.com/en-us/training/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('figma', 'Figma Education', 'Figma', 'F', '["#f24e1e","#a259ff"]', 'design', 'A', 'hot', 'approved', '$144', 144, '教育计划', '', 'ok', 1, '["UI/UX","原型","专业版免费"]', 'UI / UX / 产品设计 / 原型 / 网站 / App / AI 产品原型全覆盖，AI + 产品 + SaaS 方向强烈建议申请。', '["教育版免费解锁专业功能","设计与原型协作","AI 产品原型与交付"]', '学校邮箱申请通常可直接通过。⚠️ 两点：教育版有效期约 2 年，到期需重新验证；教育计划中 AI 功能是关闭的。免费档限制为 3 个文件，教育版解除该限制并给到完整 Professional 功能。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://www.figma.com/education/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('canva', 'Canva Education', 'Canva', 'CV', '["#00c4cc","#652cd1"]', 'design', 'B', 'conditional', 'approved', '—', 0, '教育计划', '', 'partial', 2, '["PPT","AI 图片","海报"]', 'PPT / 海报 / 社交媒体 / AI 图片 / AI 文案 / 视频，注意不同教育阶段资格不同。', '["AI 图片与 AI 文案","演示文稿与海报模板","视频与社交媒体素材"]', 'Canva Education 对不同教育阶段资格不同，大学生不一定自动获得所有 K-12 教师权益，先验证资格再决定。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://www.canva.com/education/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('adobe', 'Adobe Creative Cloud 学生版', 'Adobe', 'AD', '["#ff0000","#b30000"]', 'design', 'B', 'discount', 'approved', '大幅折扣', 0, '学生折扣订阅', '', 'ok', 2, '["PS/PR/AE","Firefly","学生价"]', '学生大幅折扣，含 Photoshop、Illustrator、Premiere Pro、After Effects、Lightroom、Acrobat、Firefly。', '["Photoshop / Illustrator / Premiere Pro / After Effects","Lightroom / Acrobat / Firefly","AI + 视频 + 图片 + 内容生产全覆盖"]', '定位是学生折扣而非免费 AI 会员。', '{"edu":true,"sheerid":false,"card":true,"vpn":false}', 'https://www.adobe.com/creativecloud/buy/students.html', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('ai-media', 'AI 创作平台（Midjourney / Runway / Suno 等）', '多平台', 'AI', '["#ff7ab6","#8b7cff"]', 'design', 'B', 'none', 'approved', '—', 0, '无统一学生计划', '', 'no', 5, '["谨慎","临时活动","勿轻信"]', '多数 AI 创作平台没有长期统一的全球学生免费会员，网上大量"学生免费一年"多为临时活动或已结束。', '["涉及：Midjourney、Runway、Pika、Kling、Luma、ElevenLabs、Suno、Udio、Gamma、Adobe Firefly","常见为临时活动 / 学校合作 / 地区活动 / 教育机构授权 / Affiliate","建议逐个查当前官方活动"]', '不要相信"学生免费 Midjourney 一年"这类标题，很多已经结束或是 Affiliate 引流。', '{"edu":true,"sheerid":false,"card":true,"vpn":true}', 'https://www.midjourney.com', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('kiro', 'AWS Kiro for Students', 'Amazon', 'KR', '["#ff9900","#7b4ddb"]', 'coding', 'S', 'hot', 'approved', '$240', 240, '免费 12 个月', '', 'hard', 3, '["1000 credits/月","免信用卡","SheerID"]', 'AWS 于 2026-09-08 把 Kiro 学生计划从 11 所大学扩到 132 所、18 个国家：每月 1,000 credits，连送 12 个月，无需信用卡。', '["每月 1,000 Kiro credits，连续 12 个月（约 $240 价值）","无需信用卡、无试用期倒计时","含付费功能：高级模型、Kiro Web（浏览器免安装）、IDE / CLI / Kiro Crew","验证方式：参与院校邮箱注册 + SheerID 一次性验证","一年后自动降级为 Kiro 免费版，不会产生费用"]', '硬性条件：18 岁以上、使用参与院校的邮箱注册、能按要求提供在读证明。credits 按月发放且不滚存，用完需等下月；学生身份验证只能做一次，信息务必填对。入口先查学校是否在名单内。', '{"edu":true,"sheerid":true,"card":false,"vpn":true}', 'https://kiro.dev/students/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('doubao', '豆包开学季学生优惠', '字节跳动', '豆', '["#5b8def","#37d6ff"]', 'ai', 'S', 'hot', 'approved', '3 个月免费', 60, '免费 3 个月订阅', '', 'ok', 1, '["大陆可用","3个月免费","开学季"]', '2026 年 9 月 1 日开学日上线：在校大学生完成学生认证后，可免费领取 3 个月豆包订阅，并可使用开学季技能专区。', '["在校大学生完成学生认证即领 3 个月免费订阅","参与官方活动还可领取额度重置机会等额外权益","开学季技能专区：新生报到、课程汇报 PPT、社团推荐、秋招求职等场景","与 8 月上旬的学生特惠可兼容：3 个月结束后仍可享学生优惠价"]', '入口：最新版豆包电脑版找到「开学免费送 3 个月」，按提示完成学生身份认证。与海外平台不同，这条中国大陆学生直接可用、无需海外网络。以客户端实际显示为准。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://www.doubao.com/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('qianwen', '千问 APP 学生/教师教育优惠', '阿里巴巴', '千', '["#615ced","#ff6a00"]', 'ai', 'A', 'discount', 'approved', '¥9.9/月起', 8, '连续 6 个月', '', 'ok', 1, '["今日上线","6个月","学生+教师"]', '2026 年 9 月 9 日上线：大学生与教师完成身份认证后，可连续 6 个月以优惠价订阅，高级会员 9.9 元/月（原价 19），精英会员 25 元/月（原价 49）。', '["高级会员 ¥9.9/月（原价 ¥19），精英会员 ¥25/月（原价 ¥49）","连续 6 个月优惠期，获取更多工作助理、PPT 生成等额度","工作助理可自主拆解任务、调用工具，完成研究分析、资料整理、网页制作、Office 文档生成","学生用于课程资料管理、课堂展示、科研申请工作台；教师用于备课与课件"]', '入口：千问 APP（7.0.7+）或 PC 端（4.2.2+）发送「我要领取教育优惠」，按指引完成身份认证。工作助理等基础功能本身免费，会员主要买的是额度。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://tongyi.aliyun.com/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('volc-ark', '火山方舟高校师生专属计划', '字节跳动 · 火山引擎', '火', '["#ff5f2e","#ffb457"]', 'cloud', 'S', 'hot', 'approved', '1 亿 Tokens', 120, '师生认证后申请', '', 'ok', 2, '["1亿 Tokens","高校师生","多模型"]', '完成师生认证即可申请，每人最高 1 亿 Tokens，覆盖豆包 Seed、DeepSeek-V4、GLM-5.2、Kimi-K2.7 等模型，额度量级在国内高校普惠里数一数二。', '["每人最高 1 亿 Tokens","覆盖豆包 Seed、DeepSeek-V4、GLM-5.2、Kimi-K2.7 等主流模型","适合课题、长文分析、Agent 开发","面向高校学生、研究生、青年教师"]', '入口在火山方舟控制台（volcengine.com/product/ark）完成师生认证后申请。这是国内少有的“大额度 + 多模型”组合，做 AI 课题的同学优先申请。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://volcengine.com/product/ark', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('tingwu', '阿里通义听悟学生认证', '阿里巴巴', '听', '["#615ced","#2f6bd8"]', 'office', 'A', 'hot', 'approved', '¥228/年', 32, '1 年免费 Pro', '', 'ok', 1, '[".edu.cn","1年 Pro","语音转写"]', '阿里出品的 AI 语音转写与会议纪要工具，用 .edu.cn 邮箱认证可享 1 年免费 Pro 会员。', '[".edu.cn 邮箱认证即得 1 年 Pro 会员（价值约 ¥228）","录音转写、会议纪要、课程内容整理","适合把网课/讲座录音转成可检索笔记"]', '需要有效的 .edu.cn 校园邮箱。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://tingwu.aliyun.com/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('dify', 'Dify.AI 教育优惠', 'Dify', 'DF', '["#1c64f2","#0b3fa8"]', 'coding', 'A', 'hot', 'approved', '¥600/年', 84, '专业版 1 年', '', 'ok', 2, '["国产","LLM 开发平台","1年专业版"]', '国产主流 LLM 应用开发平台，学生认证后赠送专业版一年使用权，适合做 RAG、Agent、工作流类项目。', '["专业版一年免费使用权（价值约 ¥600）","可视化编排 Agent 与工作流","适合课程项目、毕设、AI 应用原型"]', '以官方教育优惠页面当前政策为准。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://dify.ai/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('windsurf', 'Windsurf 学生优惠', 'Codeium', 'WS', '["#00d4aa","#0a8f75"]', 'coding', 'A', 'discount', 'approved', '$6.9/月', 97, '学生价订阅', '', 'partial', 3, '["AI IDE","原价 $15","学生价"]', 'Codeium 出品的 AI 代码编辑器，学生认证后 Pro 版约 $6.9/月（原价 $15），年省约 $97。', '["AI 代码编辑与 Agent 能力","学生价约为原价 4.6 折","可作为 Cursor 的替代选项"]', '学生权益可能随活动调整，以官方学生页为准。考虑到 Cursor 学生计划 2026 年 6 月曾有终止报道，Windsurf 值得作为备选。', '{"edu":true,"sheerid":true,"card":true,"vpn":true}', 'https://windsurf.com/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('comate', '百度文心快码 Comate 限免', '百度', 'Co', '["#2932e1","#4e6ef2"]', 'coding', 'B', 'conditional', 'approved', '不限 Token', 30, '限时活动', '2026-09-24', 'ok', 1, '["临期 9/24","不限 Token","多模型"]', 'Comate 客户端切到测试版可不限 Token 使用 9 款模型，写代码时可多模型对比；限时活动 9 月 24 日截止。', '["测试版不限 Token","9 款模型可切换对比","中国大陆直接可用"]', '临期活动，2026-09-24 截止，且限免政策可能提前调整，看到就先用。', '{"edu":false,"sheerid":false,"card":false,"vpn":false}', 'https://comate.baidu.com/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('wenxiaoyan', '文小言（文心 4.0）9 月免费', '百度', '文', '["#2932e1","#7b8cff"]', 'ai', 'B', 'conditional', 'approved', '9 月全月免费', 20, '限时活动', '2026-09-30', 'ok', 1, '["临期 9/30","文心 4.0","大陆可用"]', '文小言 9 月全月免费开放文心 4.0 全系列，老用户同样可用，9 月 30 日截止。', '["9 月全月免费使用文心 4.0 全系列","老用户同样适用","中国大陆直接可用"]', '临期活动，2026-09-30 截止。', '{"edu":false,"sheerid":false,"card":false,"vpn":false}', 'https://xiaoyan.baidu.com/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('undermind', 'undermind.ai 科研助手', 'undermind', 'UM', '["#8b5cf6","#5b21b6"]', 'search', 'B', 'discount', 'approved', 'Pro 版 5 折', 57, '学生认证价', '', 'partial', 2, '["文献检索","2.5亿论文","5折"]', 'AI 科研文献搜索工具，学生认证享 Pro 版 5 折，可深度检索约 2.5 亿篇论文。', '["深度检索约 2.5 亿篇论文","Pro 版学生 5 折（原价约 $114/年）","研究生与科研人员写综述、找文献效率高"]', '以官方教育页当前折扣为准。', '{"edu":true,"sheerid":true,"card":true,"vpn":true}', 'https://www.undermind.ai/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('bohrium', 'Bohrium 玻尔学术 AI 平台', '深势科技', 'BH', '["#0ea5e9","#0369a1"]', 'learn', 'B', 'discount', 'approved', '¥50/月档', 0, '学生认证价', '', 'ok', 2, '["国产","每日 300 光子","论文订阅"]', '深势科技出品的 AI 学术平台，学生认证后每日 300 光子额度、无限次订阅 AI 论文搜索。', '["每日 300 光子额度","无限次 AI 论文搜索订阅","适合科研、文献追踪"]', '以官方学生认证页面为准。', '{"edu":true,"sheerid":false,"card":false,"vpn":false}', 'https://bohrium.dp.tech/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO deals (id, name, vendor, letter, brand, category, tier, status, review_status, value, value_num, duration, deadline, cn, difficulty, tags, summary, highlights, notes, need, url, contact, created_at, updated_at) VALUES ('kimi-coupon', 'Kimi 新用户 API 代金券', '月之暗面', 'KM', '["#111827","#374151"]', 'ai', 'B', 'free', 'approved', '¥15 代金券', 2, '3 个月有效', '', 'ok', 1, '["新用户","15元券","长上下文"]', '月之暗面开放平台手机号实名即送 15 元无门槛代金券（3 个月有效，不可用于 K3 旗舰），网页端对话本身免费。', '["15 元无门槛 API 代金券","超长上下文，适合跑长 PDF、合同审查","网页端每日对话本来免费"]', '门槛极低但额度小，适合试用 API 与长文本场景。', '{"edu":false,"sheerid":false,"card":false,"vpn":false}', 'https://platform.moonshot.cn/', '官方录入', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
